import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NavBar} from "@/components/organisms/NavBar.organism";
import {Footer} from "@/components/organisms/Footer.organism";
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;200&display=swap" rel="stylesheet" />
    </Head>
    {children}
    </html>
  )
}
